const BASE_SUBJECT_KEYWORDS = {
  codigo: [
    // Português
    "codigo",
    "codificacao",
    "codificar",
    "codar",
    "bug",
    "debug",
    "git",
    "github",
    "commit",
    "branch",
    "merge",
    "pull request",
    "repository",
    "repositorio",
    "versao",
    "refactor",
    "refatorar",
    "clean code",
    "design pattern",
    "padroes de projeto",
    "solid",
    "api",
    "rest",
    "graphql",
    "microservices",
    "microsservicos",
    "deploy",
    "ci/cd",
    "cicd",
    "devops",
    "docker",
    "kubernetes",
    "container",
    "infra",
    "infraestrutura",
    "arquitetura",
    "teste",
    "unit test",
    "teste unitario",
    "integration",
    "integracao",
    "integration test",
    "teste de integracao",
    "tdd",
    "bdd",
    "lint",
    "prettier",
    "eslint",
    "webpack",
    "build",
    "compilacao",
    "compilation",
    "source",
    "fork",
    "clone",
    "push",
    "pull",
    "pullrequest",
    "merge request",
    "review",
    "revisao",
    "code review",
    "revisao de codigo",
    "pr",
    "pipeline",
    "ci",
    "cd",
    "rollback",
    // English
    "code",
    "coding",
    "version",
    "architecture",
    "test",
    "testing",
    "infrastructure",
    "deployment",
    // Extras
    "backend",
    "frontend",
    "monorepo",
    "monolito",
    "ddd",
    "clean architecture",
    "hexagonal",
    "ports and adapters",
    "serverless",
    "api gateway",
    // Segurança aplicada a código/arquitetura
    "seguranca",
    "security",
    "owasp",
    "oauth",
    "jwt",
    "xss",
    "csrf",
    "sql injection",
    "sqli",
    "csp",
    "tls",
    "encryption",
    "hashing",
    "rate limiting",
    "waf",
    "secrets",
    "vault",
    // UI/UX e design de produto técnico
    "ui",
    "ux",
    "user interface",
    "user experience",
    "design system",
    "component library",
    "storybook",
    "acessibilidade",
    "accessibility",
    "wcag",
    "usabilidade",
    "figma",
    "wireframe",
    "prototipo",
    // Ferramentas modernas de build/bundling
    "vite",
    "turbopack",
    "esbuild",
    "rollup",
    "parcel",
    "snowpack",
    "swc",
    "babel",
    "postcss",
    "sass",
    "less",
    "stylus",
    // Frameworks e bibliotecas adicionais
    "nextjs",
    "next.js",
    "nuxt",
    "svelte",
    "sveltekit",
    "solid",
    "solidjs",
    "qwik",
    "astro",
    "remix",
    "gatsby",
    "eleventy",
    "jekyll",
    "hugo",
    // Estado e gerenciamento
    "redux",
    "mobx",
    "zustand",
    "jotai",
    "recoil",
    "xstate",
    "state management",
    "gerenciamento de estado",
    // Testes e qualidade
    "selenium",
    "puppeteer",
    "testing library",
    "react testing library",
    "enzyme",
    "sinon",
    "chai",
    "ava",
    "tap",
    "code coverage",
    "cobertura de codigo",
    "mutation testing",
    // Metodologias e práticas
    "agile",
    "agil",
    "scrum",
    "kanban",
    "xp",
    "extreme programming",
    "pair programming",
    "programacao em par",
    "mob programming",
    "code kata",
    "kata",
    "tech debt",
    "divida tecnica",
    "refactoring",
    "refatoracao",
    // Documentação
    "swagger",
    "openapi",
    "asyncapi",
    "api documentation",
    "documentacao de api",
    "jsdoc",
    "typedoc",
    "docusaurus",
    "mkdocs",
    "sphinx",
    "readme",
    // Padrões e arquitetura
    "mvc",
    "mvvm",
    "mvp",
    "flux",
    "cqrs",
    "event sourcing",
    "saga",
    "bff",
    "backend for frontend",
    "strangler fig",
    "anti-corruption layer",
    "repository pattern",
    "factory pattern",
    "singleton",
    "observer pattern",
    "strategy pattern",
    "decorator pattern",
    // Versionamento e controle
    "semantic versioning",
    "semver",
    "changelog",
    "gitflow",
    "trunk based",
    "monorepo",
    "multirepo",
    "lerna",
    "nx",
    "turborepo",
    // Performance e otimização
    "performance",
    "otimizacao",
    "optimization",
    "caching",
    "cache",
    "cdn",
    "lazy loading",
    "code splitting",
    "tree shaking",
    "bundle size",
    "lighthouse",
    "web vitals",
    "core web vitals",
    "seo",
    // Acessibilidade
    "aria",
    "screen reader",
    "leitor de tela",
    "keyboard navigation",
    "navegacao por teclado",
    "a11y",
    // Mobile e cross-platform
    "react native",
    "flutter",
    "ionic",
    "capacitor",
    "cordova",
    "xamarin",
    "expo",
    "nativescript",
    "pwa",
    "progressive web app",
    // Desktop
    "electron",
    "tauri",
    "nwjs",
  ],
  programacao: [
    // Português
    "programacao",
    "programacoes",
    "programador",
    "programadora",
    "programar",
    "javascript",
    "python",
    "java",
    "typescript",
    "node",
    "nodejs",
    "react",
    "angular",
    "vue",
    "function",
    "funcao",
    "funcoes",
    "classe",
    "class",
    "js",
    "method",
    "metodo",
    "variavel",
    "variable",
    "loop",
    "array",
    "objeto",
    "objetos",
    "async",
    "await",
    "promise",
    "callback",
    "algorithm",
    "algoritmo",
    "algoritmos",
    "sintaxe",
    "syntax",
    "string",
    "number",
    "numero",
    "boolean",
    "booleano",
    "type",
    "tipo",
    "interface",
    "generic",
    "generico",
    "enum",
    "enumeracao",
    "struct",
    "estrutura",
    "pointer",
    "ponteiro",
    "memory",
    "memoria",
    "stack",
    "pilha",
    "heap",
    "recursion",
    "recursao",
    "iteration",
    "iteracao",
    "sorting",
    "ordenacao",
    "search",
    "busca",
    "binary",
    "binario",
    "hash",
    "tree",
    "arvore",
    "graph",
    "grafo",
    "linked list",
    "lista encadeada",
    "linkedlist",
    "queue",
    "fila",
    "map",
    "mapa",
    "set",
    "conjunto",
    "compiler",
    "compilador",
    "interpreter",
    "interpretador",
    "runtime",
    "framework",
    "library",
    "biblioteca",
    "package",
    "pacote",
    "module",
    "modulo",
    "import",
    "importar",
    "export",
    "exportar",
    "dependency",
    "dependencia",
    "npm",
    "pip",
    "maven",
    "gradle",
    "ide",
    "editor",
    "debugger",
    "depurador",
    // English
    "programming",
    "coding",
    "developer",
    "coder",
    "functions",
    "classes",
    "methods",
    "variables",
    "objects",
    "algorithms",
    "types",
    "interfaces",
    "generics",
    "enums",
    "structures",
    "pointers",
    "recursions",
    "iterations",
    "searches",
    "trees",
    "graphs",
    "queues",
    "maps",
    "sets",
    "libraries",
    "packages",
    "modules",
    "dependencies",
    // Linguagens adicionais
    "go",
    "golang",
    "rust",
    "c",
    "cpp",
    "csharp",
    "dotnet",
    "php",
    "ruby",
    "elixir",
    "kotlin",
    "swift",
    "scala",
    "r",
    // Testes
    "tests",
    "testes",
    "unit tests",
    "integration tests",
    "e2e",
    "jest",
    "mocha",
    "vitest",
    "cypress",
    "playwright",
    "testcontainers",
    "mock",
    "stub",
    "assert",
    "coverage",
    // Linguagens de programação adicionais
    "dart",
    "lua",
    "haskell",
    "ocaml",
    "fsharp",
    "clojure",
    "erlang",
    "elm",
    "purescript",
    "reasonml",
    "julia",
    "matlab",
    "fortran",
    "cobol",
    "assembly",
    "asm",
    "perl",
    "tcl",
    "bash",
    "shell script",
    "powershell",
    "vba",
    "visual basic",
    "delphi",
    "pascal",
    "ada",
    "prolog",
    "lisp",
    "scheme",
    "racket",
    // Paradigmas
    "oop",
    "orientacao a objetos",
    "object oriented",
    "functional programming",
    "programacao funcional",
    "declarative",
    "declarativo",
    "imperative",
    "imperativo",
    "procedural",
    "reactive programming",
    "programacao reativa",
    // Conceitos avançados
    "metaprogramming",
    "metaprogramacao",
    "reflection",
    "reflexao",
    "introspection",
    "introspeccao",
    "duck typing",
    "type inference",
    "inferencia de tipos",
    "covariance",
    "contravariance",
    "immutability",
    "imutabilidade",
    "pure function",
    "funcao pura",
    "side effect",
    "efeito colateral",
    "closure",
    "higher order function",
    "funcao de ordem superior",
    "currying",
    "partial application",
    "aplicacao parcial",
    "memoization",
    "memoizacao",
    "lazy evaluation",
    "avaliacao preguicosa",
    "eager evaluation",
    "tail recursion",
    "recursao de cauda",
    // Concorrência e paralelismo
    "concurrency",
    "concorrencia",
    "parallelism",
    "paralelismo",
    "threading",
    "multithreading",
    "multiprocessing",
    "coroutine",
    "corrotina",
    "green thread",
    "fiber",
    "goroutine",
    "channel",
    "mutex",
    "semaphore",
    "semaforo",
    "lock",
    "deadlock",
    "race condition",
    "condicao de corrida",
    "atomic operation",
    "operacao atomica",
    // Compiladores e interpretadores
    "lexer",
    "parser",
    "ast",
    "abstract syntax tree",
    "bytecode",
    "jit",
    "just in time",
    "aot",
    "ahead of time",
    "transpiler",
    "transpilador",
    "linker",
    "loader",
    // Gerenciamento de memória
    "garbage collection",
    "coleta de lixo",
    "reference counting",
    "contagem de referencias",
    "manual memory management",
    "gerenciamento manual de memoria",
    "memory leak",
    "vazamento de memoria",
    "buffer overflow",
    "estouro de buffer",
    // Web APIs e padrões
    "websocket",
    "webrtc",
    "service worker",
    "web worker",
    "indexeddb",
    "local storage",
    "session storage",
    "web assembly",
    "wasm",
    "fetch api",
    "xhr",
    "xmlhttprequest",
    "cors",
    "http",
    "https",
    "http2",
    "http3",
    "grpc",
    "soap",
    "xml",
    "json",
    "yaml",
    "toml",
    "protobuf",
    "avro",
    "thrift",
    // Expressões regulares
    "regex",
    "regexp",
    "regular expression",
    "expressao regular",
    "pattern matching",
    "correspondencia de padroes",
  ],
  dados: [
    // Português
    "dados",
    "dado",
    "data",
    "database",
    "banco",
    "banco de dados",
    "sql",
    "sqlserver",
    "nosql",
    "mongodb",
    "postgres",
    "postgresql",
    "mysql",
    "sqlite",
    "query",
    "consulta",
    "tabela",
    "table",
    "analytics",
    "analitica",
    "analise",
    "dashboard",
    "painel",
    "relatorio",
    "report",
    "ETL",
    "elt",
    "pipeline",
    "dataframe",
    "pandas",
    "numpy",
    "visualization",
    "visualizacao",
    "estatistica",
    "statistics",
    "ml",
    "machine learning",
    "aprendizado de maquina",
    "dataset",
    "conjunto de dados",
    "training",
    "treinamento",
    "model",
    "modelo",
    "neural",
    "deep learning",
    "aprendizado profundo",
    "ai",
    "artificial intelligence",
    "inteligencia artificial",
    "ia",
    "regression",
    "regressao",
    "classification",
    "classificacao",
    "clustering",
    "agrupamento",
    "feature",
    "caracteristica",
    "label",
    "rotulo",
    "predict",
    "prever",
    "predicao",
    "bigquery",
    "redshift",
    "snowflake",
    "spark",
    "hadoop",
    "hive",
    "kafka",
    "stream",
    "streaming",
    "transmissao",
    "batch",
    "lote",
    "warehouse",
    "armazem",
    "lake",
    "lago",
    "schema",
    "esquema",
    "index",
    "indice",
    "join",
    "juncao",
    "aggregate",
    "agregacao",
    "group by",
    "agrupar",
    "partition",
    "particao",
    "normalization",
    "normalizacao",
    "denormalization",
    "desnormalizacao",
    "databricks",
    "lakehouse",
    "powerbi",
    "bi",
    "metadado",
    "metadata",
    // English
    "databases",
    "tables",
    "queries",
    "dashboards",
    "reports",
    "analysis",
    "models",
    "predictions",
    "features",
    "labels",
    "clusters",
    "regressions",
    "classifications",
    "indexes",
    "joins",
    "aggregates",
    "partitions",
    // Ferramentas e plataformas de dados
    "looker",
    "looker studio",
    "metabase",
    "superset",
    "dbt",
    "airflow",
    "dagster",
    "great expectations",
    "synapse",
    "glue",
    "emr",
    // IA e Machine Learning expandido
    "tensorflow",
    "pytorch",
    "keras",
    "scikit-learn",
    "sklearn",
    "xgboost",
    "lightgbm",
    "catboost",
    "hugging face",
    "transformers",
    "bert",
    "gpt",
    "llm",
    "large language model",
    "nlp",
    "natural language processing",
    "processamento de linguagem natural",
    "computer vision",
    "visao computacional",
    "opencv",
    "yolo",
    "cnn",
    "convolutional neural network",
    "rede neural convolucional",
    "rnn",
    "recurrent neural network",
    "rede neural recorrente",
    "lstm",
    "gru",
    "attention mechanism",
    "mecanismo de atencao",
    "transformer",
    "autoencoder",
    "gan",
    "generative adversarial network",
    "rede adversarial generativa",
    "reinforcement learning",
    "aprendizado por reforco",
    "supervised learning",
    "aprendizado supervisionado",
    "unsupervised learning",
    "aprendizado nao supervisionado",
    "semi-supervised learning",
    "aprendizado semi-supervisionado",
    "transfer learning",
    "aprendizado por transferencia",
    "fine-tuning",
    "ajuste fino",
    "hyperparameter",
    "hiperparametro",
    "overfitting",
    "sobreajuste",
    "underfitting",
    "subajuste",
    "cross-validation",
    "validacao cruzada",
    "confusion matrix",
    "matriz de confusao",
    "precision",
    "precisao",
    "recall",
    "revocacao",
    "f1 score",
    "roc curve",
    "auc",
    "gradient descent",
    "descida de gradiente",
    "backpropagation",
    "retropropagacao",
    "epoch",
    "epoca",
    "batch",
    "mini-batch",
    "learning rate",
    "taxa de aprendizado",
    "optimizer",
    "otimizador",
    "adam",
    "sgd",
    "stochastic gradient descent",
    "dropout",
    "batch normalization",
    "normalizacao em lote",
    "activation function",
    "funcao de ativacao",
    "relu",
    "sigmoid",
    "tanh",
    "softmax",
    // Bancos de dados adicionais
    "cassandra",
    "couchdb",
    "neo4j",
    "orientdb",
    "arangodb",
    "dgraph",
    "rethinkdb",
    "influxdb",
    "timescaledb",
    "clickhouse",
    "druid",
    "elasticsearch",
    "solr",
    "redis",
    "memcached",
    "dynamodb",
    "cosmosdb",
    "firestore",
    "realm",
    "cockroachdb",
    "yugabytedb",
    "vitess",
    "tidb",
    "mariadb",
    "percona",
    "aurora",
    "oracle",
    "db2",
    "teradata",
    "vertica",
    "greenplum",
    // Modelagem de dados
    "er diagram",
    "diagrama er",
    "entity relationship",
    "relacionamento de entidades",
    "data modeling",
    "modelagem de dados",
    "star schema",
    "esquema estrela",
    "snowflake schema",
    "esquema floco de neve",
    "fact table",
    "tabela fato",
    "dimension table",
    "tabela dimensao",
    "olap",
    "oltp",
    "acid",
    "base",
    "cap theorem",
    "teorema cap",
    "sharding",
    "fragmentacao",
    "replication",
    "replicacao",
    "master-slave",
    "master-master",
    "read replica",
    "replica de leitura",
    "connection pool",
    "pool de conexoes",
    "transaction",
    "transacao",
    "commit",
    "rollback",
    "savepoint",
    "isolation level",
    "nivel de isolamento",
    "deadlock",
    "lock timeout",
    // Processamento de dados
    "map reduce",
    "mapreduce",
    "apache flink",
    "apache storm",
    "apache samza",
    "apache beam",
    "data pipeline",
    "pipeline de dados",
    "data lake",
    "lago de dados",
    "data mesh",
    "malha de dados",
    "data fabric",
    "tecido de dados",
    "data catalog",
    "catalogo de dados",
    "data lineage",
    "linhagem de dados",
    "data quality",
    "qualidade de dados",
    "data governance",
    "governanca de dados",
    "master data management",
    "mdm",
    "data cleansing",
    "limpeza de dados",
    "data transformation",
    "transformacao de dados",
    "data enrichment",
    "enriquecimento de dados",
    "data masking",
    "mascaramento de dados",
    "data anonymization",
    "anonimizacao de dados",
    // Análise e visualização
    "tableau",
    "qlik",
    "power bi",
    "grafana",
    "kibana",
    "redash",
    "apache superset",
    "plotly",
    "d3.js",
    "chart.js",
    "highcharts",
    "matplotlib",
    "seaborn",
    "ggplot",
    "bokeh",
    "altair",
    "kpi",
    "key performance indicator",
    "indicador chave de desempenho",
    "metric",
    "metrica",
    "dimension",
    "dimensao",
    "measure",
    "medida",
    "drill down",
    "drill through",
    "slice and dice",
    // Jupyter e notebooks
    "jupyter",
    "notebook",
    "jupyterlab",
    "jupyter notebook",
    "ipython",
    "colab",
    "google colab",
    "kaggle",
    "databricks notebook",
    "zeppelin",
    "apache zeppelin",
    // Feature engineering
    "feature engineering",
    "engenharia de features",
    "feature selection",
    "selecao de features",
    "feature extraction",
    "extracao de features",
    "dimensionality reduction",
    "reducao de dimensionalidade",
    "pca",
    "principal component analysis",
    "analise de componentes principais",
    "t-sne",
    "umap",
    "scaling",
    "escalamento",
    "standardization",
    "padronizacao",
    "normalization",
    "one-hot encoding",
    "codificacao one-hot",
    "label encoding",
    "codificacao de rotulos",
    "binning",
    "discretizacao",
    "imputation",
    "imputacao",
    "outlier detection",
    "deteccao de outliers",
    "anomaly detection",
    "deteccao de anomalias",
  ],
  devops: [
    // Português
    "devops",
    "infra",
    "infraestrutura",
    "observabilidade",
    "monitoramento",
    "alerta",
    "confiabilidade",
    "sre",
    "deploy",
    "pipeline",
    "entrega continua",
    "integracao continua",
    "orquestracao",
    // Ferramentas/Conceitos
    "ci",
    "cd",
    "cicd",
    "ci/cd",
    "terraform",
    "iac",
    "ansible",
    "pulumi",
    "kubernetes",
    "helm",
    "argo",
    "argo cd",
    "flux",
    "docker",
    "container",
    "containers",
    "prometheus",
    "grafana",
    "loki",
    "tempo",
    "jaeger",
    "otel",
    "open telemetry",
    "feature flag",
    // Cloud
    "cloud",
    "aws",
    "azure",
    "gcp",
    "serverless",
    "lambda",
    "cloud run",
    "functions",
    // Segurança, suporte e operações
    "seguranca",
    "security",
    "iam",
    "kms",
    "vault",
    "waf",
    "ddos",
    "sast",
    "dast",
    "sonarqube",
    "snyk",
    "dependabot",
    "guardduty",
    "cloudtrail",
    "inspector",
    "policy",
    // Suporte/operacao
    "suporte",
    "support",
    "incidente",
    "incident",
    "oncall",
    "on-call",
    "postmortem",
    "runbook",
    "playbook",
    "sla",
    "slo",
    "sli",
    // Kubernetes avançado
    "kubectl",
    "kustomize",
    "helm chart",
    "operator",
    "crd",
    "custom resource definition",
    "pod",
    "deployment",
    "statefulset",
    "daemonset",
    "job",
    "cronjob",
    "service",
    "ingress",
    "configmap",
    "secret",
    "persistent volume",
    "pv",
    "pvc",
    "namespace",
    "node",
    "cluster",
    "replica",
    "rolling update",
    "rollback",
    "horizontal pod autoscaler",
    "hpa",
    "vertical pod autoscaler",
    "vpa",
    "network policy",
    "service mesh",
    "istio",
    "linkerd",
    "consul",
    "envoy",
    // CI/CD expandido
    "jenkins",
    "gitlab ci",
    "github actions",
    "circle ci",
    "travis ci",
    "bamboo",
    "teamcity",
    "azure devops",
    "azure pipelines",
    "bitbucket pipelines",
    "drone",
    "spinnaker",
    "tekton",
    "concourse",
    "buildkite",
    "continuous deployment",
    "implantacao continua",
    "blue-green deployment",
    "canary deployment",
    "canary release",
    "progressive delivery",
    "entrega progressiva",
    "feature toggle",
    "feature flag",
    "trunk based development",
    "gitops",
    // Infraestrutura como código
    "cloudformation",
    "bicep",
    "arm template",
    "cdk",
    "cloud development kit",
    "crossplane",
    "terraform cloud",
    "terraform enterprise",
    "atlantis",
    "terragrunt",
    "ansible playbook",
    "ansible role",
    "ansible galaxy",
    "chef",
    "puppet",
    "saltstack",
    // Containers e registry
    "dockerfile",
    "docker compose",
    "docker swarm",
    "containerd",
    "cri-o",
    "podman",
    "buildah",
    "skopeo",
    "docker hub",
    "docker registry",
    "harbor",
    "quay",
    "ecr",
    "elastic container registry",
    "acr",
    "azure container registry",
    "gcr",
    "google container registry",
    "artifactory",
    "nexus",
    // Observabilidade expandida
    "prometheus",
    "alertmanager",
    "thanos",
    "cortex",
    "mimir",
    "victoria metrics",
    "grafana loki",
    "grafana tempo",
    "grafana mimir",
    "opentelemetry",
    "otel collector",
    "jaeger",
    "zipkin",
    "datadog",
    "new relic",
    "dynatrace",
    "appdynamics",
    "elastic apm",
    "splunk",
    "sumologic",
    "logging",
    "log aggregation",
    "agregacao de logs",
    "metrics",
    "metricas",
    "traces",
    "rastros",
    "distributed tracing",
    "rastreamento distribuido",
    "span",
    "trace context",
    "contexto de rastro",
    "instrumentation",
    "instrumentacao",
    "telemetry",
    "telemetria",
    "slo",
    "service level objective",
    "objetivo de nivel de servico",
    "sli",
    "service level indicator",
    "indicador de nivel de servico",
    "sla",
    "service level agreement",
    "acordo de nivel de servico",
    "error budget",
    "orcamento de erros",
    // Cloud providers expandido
    "ec2",
    "s3",
    "rds",
    "dynamodb",
    "lambda",
    "api gateway",
    "cloudfront",
    "route53",
    "vpc",
    "iam",
    "cloudwatch",
    "cloudtrail",
    "eks",
    "ecs",
    "fargate",
    "elastic beanstalk",
    "amplify",
    "cognito",
    "sns",
    "sqs",
    "kinesis",
    "athena",
    "emr",
    "glue",
    "sagemaker",
    "azure vm",
    "azure blob storage",
    "azure sql",
    "azure cosmos db",
    "azure functions",
    "azure app service",
    "azure kubernetes service",
    "aks",
    "azure container instances",
    "aci",
    "azure devops",
    "azure monitor",
    "application insights",
    "gce",
    "google compute engine",
    "gcs",
    "google cloud storage",
    "cloud sql",
    "bigquery",
    "cloud functions",
    "cloud run",
    "gke",
    "google kubernetes engine",
    "cloud build",
    "cloud logging",
    "cloud monitoring",
    "cloud trace",
    // Segurança DevOps
    "devsecops",
    "shift left",
    "deslocar para esquerda",
    "security scanning",
    "varredura de seguranca",
    "vulnerability scanning",
    "varredura de vulnerabilidades",
    "sast",
    "static application security testing",
    "dast",
    "dynamic application security testing",
    "iast",
    "interactive application security testing",
    "rasp",
    "runtime application self-protection",
    "sbom",
    "software bill of materials",
    "cve",
    "common vulnerabilities and exposures",
    "cvss",
    "penetration testing",
    "teste de penetracao",
    "pen test",
    "red team",
    "blue team",
    "purple team",
    "threat modeling",
    "modelagem de ameacas",
    "attack surface",
    "superficie de ataque",
    "zero trust",
    "confianca zero",
    "least privilege",
    "privilegio minimo",
    "rbac",
    "role based access control",
    "controle de acesso baseado em funcoes",
    "identity and access management",
    "gerenciamento de identidade e acesso",
    "secrets management",
    "gerenciamento de segredos",
    "hashicorp vault",
    "aws secrets manager",
    "azure key vault",
    "google secret manager",
    "sealed secrets",
    "external secrets",
    "certificate management",
    "gerenciamento de certificados",
    "cert-manager",
    "let's encrypt",
    "acme",
    "mtls",
    "mutual tls",
    // Disaster Recovery e Backup
    "disaster recovery",
    "recuperacao de desastres",
    "backup",
    "restore",
    "restauracao",
    "rpo",
    "recovery point objective",
    "objetivo de ponto de recuperacao",
    "rto",
    "recovery time objective",
    "objetivo de tempo de recuperacao",
    "high availability",
    "alta disponibilidade",
    "failover",
    "chaos engineering",
    "engenharia do caos",
    "chaos monkey",
    "fault injection",
    "injecao de falhas",
    "resilience",
    "resiliencia",
    "circuit breaker",
    "disjuntor",
    "retry",
    "retentativa",
    "timeout",
    "tempo limite",
    "bulkhead",
    "anteparo",
    // Networking
    "load balancer",
    "balanceador de carga",
    "reverse proxy",
    "proxy reverso",
    "nginx",
    "haproxy",
    "traefik",
    "envoy proxy",
    "cdn",
    "content delivery network",
    "rede de entrega de conteudo",
    "dns",
    "domain name system",
    "tcp",
    "udp",
    "ip",
    "ipv4",
    "ipv6",
    "subnet",
    "sub-rede",
    "firewall",
    "nat",
    "network address translation",
    "vpn",
    "virtual private network",
    "vlan",
    "virtual lan",
    "bgp",
    "border gateway protocol",
    "peering",
    "emparelhamento",
    // Compliance e auditoria
    "compliance",
    "conformidade",
    "audit",
    "auditoria",
    "gdpr",
    "lgpd",
    "hipaa",
    "pci dss",
    "soc 2",
    "iso 27001",
    "nist",
    "cis benchmark",
    "benchmark cis",
    "hardening",
    "endurecimento",
    "baseline",
    "linha de base",
    "patch management",
    "gerenciamento de patches",
    "vulnerability management",
    "gerenciamento de vulnerabilidades",
    // Automação e scripting
    "automation",
    "automacao",
    "scripting",
    "bash script",
    "python script",
    "powershell script",
    "makefile",
    "task runner",
    "executor de tarefas",
    "cron",
    "crontab",
    "systemd",
    "init",
    "supervisor",
    "pm2",
    "forever",
    // Performance e tuning
    "performance tuning",
    "ajuste de desempenho",
    "profiling",
    "perfilamento",
    "benchmarking",
    "benchmark",
    "stress test",
    "teste de estresse",
    "load test",
    "teste de carga",
    "capacity planning",
    "planejamento de capacidade",
    "scaling",
    "escalamento",
    "horizontal scaling",
    "escalamento horizontal",
    "vertical scaling",
    "escalamento vertical",
    "auto scaling",
    "autoescalamento",
    "throttling",
    "limitacao",
    "backpressure",
    "contrapressao",
    "queue",
    "fila",
    "message queue",
    "fila de mensagens",
    "rabbitmq",
    "activemq",
    "nats",
    "zeromq",
    "redis pub/sub",
    "event bus",
    "barramento de eventos",
  ],
};

module.exports = BASE_SUBJECT_KEYWORDS;
