const OFF_TOPIC_KEYWORDS = [
  // Culinária e alimentação (PT + EN)
  "receita",
  "culinaria",
  "comida",
  "food",
  "recipe",
  "cozinha",
  "kitchen",
  "ingrediente",
  "ingredient",
  "cozinhar",
  "cooking",
  "prato",
  "dish",
  "refeicao",
  "meal",
  // Bebidas e gastronomia
  "restaurante",
  "bar",
  "cafeteria",
  "cafe",
  "chá",
  "cha",
  "vinho",
  "cerveja",
  "drink",
  "coquetel",
  "coquetéis",
  "sommelier",
  "gastronomia",
  "vegano",
  "vegetariano",
  "sem glúten",
  "sem lactose",

  // Esportes e entretenimento (PT + EN)
  "futebol",
  "football",
  "soccer",
  "esporte",
  "sport",
  "jogo",
  "game",
  "clube",
  "club",
  "time",
  "team",
  "campeonato",
  "championship",
  "partida",
  "match",
  "jogador",
  "player",
  // Outros esportes
  "basquete",
  "basketball",
  "volei",
  "vôlei",
  "volleyball",
  "tenis",
  "tênis",
  "golf",
  "golfe",
  "natacao",
  "natação",
  "corrida",
  "running",
  "ciclismo",
  "cycling",
  "mma",
  "boxe",
  "boxing",
  "muay thai",
  "skate",
  "surfe",
  "surf",
  "maratona",
  "triatlo",
  "triatlon",
  "esqui",
  "snowboard",
  "beisebol",
  "baseball",
  "hockey",
  "hóquei",
  "olimpiada",
  "olimpíada",
  "olympics",

  // Política (PT + EN)
  "politica",
  "politics",
  "eleicao",
  "election",
  "governo",
  "government",
  "president",
  "presidente",
  "partido",
  "party",
  "deputado",
  "senador",
  "voto",
  "vote",
  "prefeito",
  "governador",
  "congresso",
  "parlamento",
  "ministro",
  "ministra",
  "politico",
  "politicos",
  "político",
  "políticos",

  // Saúde e medicina (PT + EN)
  "saude",
  "health",
  "medico",
  "doctor",
  "medicina",
  "medicine",
  "doenca",
  "disease",
  "sintoma",
  "symptom",
  "remedio",
  "remedy",
  "tratamento",
  "treatment",
  "hospital",
  "clinica",
  "clinic",
  // Bem-estar e fitness
  "bem estar",
  "bem-estar",
  "academia",
  "gym",
  "musculacao",
  "musculação",
  "treino",
  "treinamento fisico",
  "personal trainer",
  "dieta",
  "emagrecer",
  "perder peso",
  "nutricao",
  "nutrição",
  "nutricionista",
  "caloria",
  "calorias",
  "proteina",
  "proteína",
  "carboidrato",
  "carboidratos",
  "gordura",
  "jejum intermitente",
  "yoga",
  "pilates",
  "crossfit",
  "alongamento",
  "meditacao",
  "meditação",
  "saude mental",
  "saúde mental",
  "ansiedade",
  "depressao",
  "depressão",
  "terapia",
  "psicologo",
  "psicóloga",
  "psicologo",
  "psicóloga",

  // Clima e meteorologia (PT + EN)
  "clima",
  "climate",
  "weather",
  "tempo",
  "temperatura",
  "temperature",
  "chuva",
  "rain",
  "previsao",
  "forecast",
  "sol",
  "sun",
  "nuvem",
  "cloud",
  // Natureza e meio ambiente
  "meio ambiente",
  "ecologia",
  "sustentabilidade",
  "reciclagem",
  "reciclar",
  "desmatamento",
  "aquecimento global",
  "mudanca climatica",
  "mudança climática",
  "estacoes",
  "estações",
  "primavera",
  "verao",
  "verão",
  "outono",
  "inverno",
  "terremoto",
  "furacao",
  "furacão",
  "tornado",
  "tsunami",

  // Moda e estilo (PT + EN)
  "moda",
  "fashion",
  "roupa",
  "clothes",
  "clothing",
  "estilo",
  "style",
  "look",
  "vestido",
  "dress",
  "sapato",
  "shoe",
  // Beleza e cuidados
  "beleza",
  "maquiagem",
  "skincare",
  "cabelo",
  "penteado",
  "barbear",
  "barba",
  "perfume",
  "unha",
  "manicure",
  "pedicure",

  // Viagem e turismo (PT + EN)
  "viagem",
  "travel",
  "trip",
  "turismo",
  "tourism",
  "hotel",
  "passagem",
  "ticket",
  "destino",
  "destination",
  "voo",
  "flight",
  // Viagem — extra
  "aeroporto",
  "aviao",
  "avião",
  "passaporte",
  "visto",
  "aluguel de carro",
  "airbnb",
  "hostel",
  "mochileiro",
  "roteiro",
  "bagagem",

  // RH e carreira (não técnica) (PT + EN)
  "entrevista",
  "interview",
  "curriculo",
  "cv",
  "resume",
  "contratar",
  "hire",
  "hiring",
  "recrutamento",
  "recruitment",
  "recursos humanos",
  "human resources",
  "salario",
  "salary",
  "beneficio",
  "benefit",
  "ferias",
  "vacation",
  "holidays",
  // Trabalho e carreira não técnica
  "emprego",
  "vaga",
  "promocao",
  "promoção",
  "lideranca",
  "liderança",
  "gestao",
  "gestão",
  "chefe",
  "coaching",
  "mentoria",
  "apresentacao",
  "apresentação",

  // Finanças pessoais (PT + EN)
  "investimento",
  "investment",
  "bolsa",
  "acao",
  "stock",
  "financeiro",
  "financial",
  "dinheiro",
  "money",
  "emprestimo",
  "loan",
  "credito",
  "credit",
  // Finanças — extra
  "orcamento",
  "orçamento",
  "poupanca",
  "poupança",
  "divida",
  "dívida",
  "juros",
  "imposto",
  "irpf",
  "contabilidade",
  "conta corrente",
  "cartao de credito",
  "cartão de crédito",
  "pix",
  "boleto",

  // Relacionamentos e vida pessoal (PT + EN)
  "namoro",
  "dating",
  "casamento",
  "marriage",
  "wedding",
  "relacionamento",
  "relationship",
  "familia",
  "family",
  "amigo",
  "friend",
  "amor",
  "love",
  // Relacionamentos — extra
  "maternidade",
  "paternidade",
  "gravidez",
  "bebe",
  "bebê",
  "criança",
  "crianca",
  "adolescente",
  "casal",
  "separacao",
  "separação",
  "divorcio",
  "divórcio",
  "conselho amoroso",
  "amizade",

  // Educação geral (não técnica) (PT + EN)
  "matematica",
  "mathematics",
  "math",
  "historia",
  "history",
  "geografia",
  "geography",
  "literatura",
  "literature",
  "redacao",
  "essay",
  "writing",
  // Educação — extra
  "escola",
  "faculdade",
  "universidade",
  "curso",
  "aula",
  "professor",
  "professora",
  "aluno",
  "aluna",
  "prova",
  "trabalho escolar",
  "tarefa de casa",
  "dever de casa",
  "vestibular",
  "enem",
  "idiomas",
  "ingles",
  "inglês",
  "espanhol",
  "frances",
  "francês",
  "alemao",
  "alemão",

  // Entretenimento (PT + EN)
  "filme",
  "movie",
  "film",
  "serie",
  "series",
  "show",
  "musica",
  "music",
  "livro",
  "book",
  "novela",
  "soap opera",
  // Entretenimento — extra
  "celebridade",
  "celebridades",
  "famoso",
  "famosa",
  "gossip",
  "fofoca",
  "streaming",
  "netflix",
  "disney+",
  "prime video",
  "spotify",
  "videogame",
  "video game",
  "tabuleiro",
  "jogo de tabuleiro",
  "podcast",
  "stand-up",
  "comedia",
  "comédia",
  "humor",
  "meme",

  // Outros (PT + EN)
  "religiao",
  "religion",
  "filosofia",
  "philosophy",
  "psychology",
  "psicologia",
  "astrologia",
  "astrology",
  // Espiritualidade e religião — extra
  "cristianismo",
  "catolico",
  "católico",
  "evangelico",
  "evangélico",
  "protestante",
  "judaísmo",
  "judaismo",
  "islamismo",
  "budismo",
  "hinduismo",
  "umbanda",
  "candomble",
  "candomblé",
  "oracao",
  "oração",
  "missa",
  "culto",
  "horoscopo",
  "horóscopo",
  // Animais e pets
  "animal",
  "animais",
  "pet",
  "pets",
  "cachorro",
  "cao",
  "cão",
  "gato",
  "passaro",
  "pássaro",
  "papagaio",
  "veterinario",
  "veterinária",
  "veterinario",
  "veterinária",
  "raca",
  "raça",
  // Casa, família e cotidiano
  "casa",
  "lar",
  "familia",
  "família",
  "casamento",
  "decoracao",
  "decoração",
  "design de interiores",
  "reforma",
  "limpeza",
  "organizacao",
  "organização",
  "jardinagem",
  "horta",
  "plantas",
  "planta",
  // Hobbies e artes
  "fotografia",
  "foto",
  "camera",
  "câmera",
  "pintura",
  "desenho",
  "aquarela",
  "escultura",
  "teatro",
  "danca",
  "dança",
  "ballet",
  "violao",
  "violão",
  "guitarra",
  "piano",
  "bateria",
  "canto",
  "artesanato",
  "tricô",
  "trico",
  "crochê",
  "croche",
  "costura",
  "origami",
  // Automotivo
  "carro",
  "moto",
  "automovel",
  "automóvel",
  "mecanica",
  "mecânica",
  "oficina",
  "manutencao",
  "manutenção",
  "gasolina",
  "diesel",
  "transito",
  "trânsito",
  "multa",
  "cnh",
  "carteira de motorista",
  // Imobiliário
  "aluguel",
  "alugar",
  "comprar casa",
  "vender casa",
  "hipoteca",
  "imobiliaria",
  "imobiliária",
  "corretor",
  "condominio",
  "condomínio",
  // Direito e temas legais
  "advogado",
  "advogada",
  "processo",
  "processar",
  "contrato",
  "leis",
  "lei",
  "legislacao",
  "legislação",
  "justica",
  "justiça",
  "tribunal",
  "juiz",
  // Jogos de azar
  "loteria",
  "aposta",
  "apostas",
  "cassino",
  "casino",
  "poker",
  "pôquer",
  "bet",
  // Mídia e notícias
  "jornal",
  "noticia",
  "notícia",
  "reportagem",
  "revista",
  "televisao",
  "televisão",
  "tv",
  "radio",
  "rádio",
  // Adulto (bloqueio geral)
  "conteudo adulto",
  "conteúdo adulto",
  "adulto",
  "erotico",
  "erótico",
  "pornografia",
  "porn",
  "sexo",
  "sexual",
  // Vida ao ar livre
  "trilha",
  "camping",
  "acampamento",
  "pescaria",
  "pesca",
  "caca",
  "caça",
  // Marketing e negócios não técnicos
  "marketing",
  "vendas",
  "publicidade",
  "propaganda",
  "branding",
  "influenciador",
  "influencer",
  "redes sociais",
  "instagram",
  "tiktok",
  "youtube",
  "facebook",
];

module.exports = OFF_TOPIC_KEYWORDS;
